/*
    Create a new table using the CREATE TABLE command. Use your first name and your last name for the name of the table (for instance, for John Smith the name of the table will be JOHN_SMITH). Make sure to include at least four different data types (CHAR, VARCHAR2, NUMBER, DATE) for the columns and appropriate constraints (PK, FK, NOT NULL, CHECK, UNIQUE). Use the DESCRIBE command to verify that the columns have been defined correctly.
    Use the INSERT command to insert a new record into the table created in Problem 1. When inserting a record, provide values for all columns. Use the default format for the date. Use the SELECT * FROM your_table_name; command to display the content of the table (make sure to substitute your_table_name with the actual name of your table).
    Use the INSERT command to insert a new record into the table created in Problem 1. When inserting a record, provide values for selected columns only. Use the default format for the date. Use the SELECT * FROM your_table_name; command to display the content of the table (make sure to substitute your_table_name with the actual name of your table).
    Use the UPDATE command to update multiple values in the table created in Problem 1. Use the SELECT * FROM your_table_name; command to display the content of the table (make sure to substitute your_table_name with the actual name of your table).
    Use the DELETE command to delete one specific row from the table created in Problem 1. Use the SELECT * FROM your_table_name; command to display the content of the table (make sure to substitute your_table_name with the actual name of your table).
    Use the COMMIT statement to save changes in the table created in Problem 1. Use the SELECT * FROM your_table_name; command to display the content of the table (make sure to substitute your_table_name with the actual name of your table).
    Use the ROLLBACK command to undo changes in the table created in Problem 1. What happened? Why? Use the SELECT * FROM your_table_name; command to display the content of the table (make sure to substitute your_table_name with the actual name of your table).
    Use the DROP TABLE command to drop the table created in Problem 1.
*/